[XC2ZIAInput::IBuf{ibuf: 0},
 XC2ZIAInput::IBuf{ibuf: 10},
 XC2ZIAInput::IBuf{ibuf: 21},
 XC2ZIAInput::Macrocell{fb: 0, mc: 1},
 XC2ZIAInput::Macrocell{fb: 0, mc: 13},
 XC2ZIAInput::Macrocell{fb: 1, mc: 9}],

[XC2ZIAInput::IBuf{ibuf: 1},
 XC2ZIAInput::IBuf{ibuf: 11},
 XC2ZIAInput::IBuf{ibuf: 22},
 XC2ZIAInput::Macrocell{fb: 0, mc: 8},
 XC2ZIAInput::Macrocell{fb: 0, mc: 15},
 XC2ZIAInput::Macrocell{fb: 1, mc: 12}],

[XC2ZIAInput::IBuf{ibuf: 2},
 XC2ZIAInput::IBuf{ibuf: 12},
 XC2ZIAInput::IBuf{ibuf: 29},
 XC2ZIAInput::Macrocell{fb: 0, mc: 2},
 XC2ZIAInput::Macrocell{fb: 1, mc: 4},
 XC2ZIAInput::Macrocell{fb: 1, mc: 11}],

[XC2ZIAInput::IBuf{ibuf: 3},
 XC2ZIAInput::IBuf{ibuf: 13},
 XC2ZIAInput::IBuf{ibuf: 25},
 XC2ZIAInput::Macrocell{fb: 0, mc: 9},
 XC2ZIAInput::Macrocell{fb: 0, mc: 14},
 XC2ZIAInput::Macrocell{fb: 1, mc: 6}],

[XC2ZIAInput::IBuf{ibuf: 4},
 XC2ZIAInput::IBuf{ibuf: 14},
 XC2ZIAInput::IBuf{ibuf: 27},
 XC2ZIAInput::Macrocell{fb: 0, mc: 5},
 XC2ZIAInput::Macrocell{fb: 0, mc: 11},
 XC2ZIAInput::Macrocell{fb: 1, mc: 10}],

[XC2ZIAInput::IBuf{ibuf: 5},
 XC2ZIAInput::IBuf{ibuf: 15},
 XC2ZIAInput::IBuf{ibuf: 30},
 XC2ZIAInput::Macrocell{fb: 0, mc: 7},
 XC2ZIAInput::Macrocell{fb: 1, mc: 1},
 XC2ZIAInput::Macrocell{fb: 1, mc: 7}],

[XC2ZIAInput::IBuf{ibuf: 6},
 XC2ZIAInput::DedicatedInput,
 XC2ZIAInput::IBuf{ibuf: 20},
 XC2ZIAInput::Macrocell{fb: 0, mc: 0},
 XC2ZIAInput::Macrocell{fb: 1, mc: 3},
 XC2ZIAInput::Macrocell{fb: 1, mc: 13}],

[XC2ZIAInput::IBuf{ibuf: 7},
 XC2ZIAInput::IBuf{ibuf: 16},
 XC2ZIAInput::IBuf{ibuf: 26},
 XC2ZIAInput::IBuf{ibuf: 31},
 XC2ZIAInput::Macrocell{fb: 0, mc: 12},
 XC2ZIAInput::Macrocell{fb: 1, mc: 15}],

[XC2ZIAInput::IBuf{ibuf: 8},
 XC2ZIAInput::IBuf{ibuf: 17},
 XC2ZIAInput::IBuf{ibuf: 24},
 XC2ZIAInput::Macrocell{fb: 0, mc: 6},
 XC2ZIAInput::Macrocell{fb: 0, mc: 10},
 XC2ZIAInput::Macrocell{fb: 1, mc: 8}],

[XC2ZIAInput::IBuf{ibuf: 9},
 XC2ZIAInput::IBuf{ibuf: 18},
 XC2ZIAInput::IBuf{ibuf: 23},
 XC2ZIAInput::Macrocell{fb: 0, mc: 4},
 XC2ZIAInput::Macrocell{fb: 1, mc: 2},
 XC2ZIAInput::Macrocell{fb: 1, mc: 5}],

[XC2ZIAInput::IBuf{ibuf: 7},
 XC2ZIAInput::IBuf{ibuf: 19},
 XC2ZIAInput::IBuf{ibuf: 28},
 XC2ZIAInput::Macrocell{fb: 0, mc: 3},
 XC2ZIAInput::Macrocell{fb: 1, mc: 0},
 XC2ZIAInput::Macrocell{fb: 1, mc: 14}],

[XC2ZIAInput::IBuf{ibuf: 0},
 XC2ZIAInput::IBuf{ibuf: 11},
 XC2ZIAInput::IBuf{ibuf: 22},
 XC2ZIAInput::Macrocell{fb: 0, mc: 2},
 XC2ZIAInput::Macrocell{fb: 0, mc: 14},
 XC2ZIAInput::Macrocell{fb: 1, mc: 10}],

[XC2ZIAInput::IBuf{ibuf: 1},
 XC2ZIAInput::IBuf{ibuf: 12},
 XC2ZIAInput::IBuf{ibuf: 29},
 XC2ZIAInput::Macrocell{fb: 0, mc: 4},
 XC2ZIAInput::Macrocell{fb: 1, mc: 1},
 XC2ZIAInput::Macrocell{fb: 1, mc: 15}],

[XC2ZIAInput::IBuf{ibuf: 2},
 XC2ZIAInput::IBuf{ibuf: 18},
 XC2ZIAInput::IBuf{ibuf: 23},
 XC2ZIAInput::Macrocell{fb: 0, mc: 9},
 XC2ZIAInput::Macrocell{fb: 1, mc: 0},
 XC2ZIAInput::Macrocell{fb: 1, mc: 13}],

[XC2ZIAInput::IBuf{ibuf: 3},
 XC2ZIAInput::IBuf{ibuf: 15},
 XC2ZIAInput::IBuf{ibuf: 30},
 XC2ZIAInput::Macrocell{fb: 0, mc: 3},
 XC2ZIAInput::Macrocell{fb: 0, mc: 11},
 XC2ZIAInput::Macrocell{fb: 1, mc: 12}],

[XC2ZIAInput::IBuf{ibuf: 4},
 XC2ZIAInput::IBuf{ibuf: 16},
 XC2ZIAInput::IBuf{ibuf: 26},
 XC2ZIAInput::Macrocell{fb: 0, mc: 0},
 XC2ZIAInput::Macrocell{fb: 0, mc: 15},
 XC2ZIAInput::Macrocell{fb: 1, mc: 7}],

[XC2ZIAInput::IBuf{ibuf: 5},
 XC2ZIAInput::IBuf{ibuf: 19},
 XC2ZIAInput::IBuf{ibuf: 28},
 XC2ZIAInput::Macrocell{fb: 0, mc: 6},
 XC2ZIAInput::Macrocell{fb: 0, mc: 12},
 XC2ZIAInput::Macrocell{fb: 1, mc: 11}],

[XC2ZIAInput::IBuf{ibuf: 6},
 XC2ZIAInput::IBuf{ibuf: 10},
 XC2ZIAInput::IBuf{ibuf: 21},
 XC2ZIAInput::Macrocell{fb: 0, mc: 8},
 XC2ZIAInput::Macrocell{fb: 1, mc: 2},
 XC2ZIAInput::Macrocell{fb: 1, mc: 8}],

[XC2ZIAInput::IBuf{ibuf: 7},
 XC2ZIAInput::DedicatedInput,
 XC2ZIAInput::IBuf{ibuf: 20},
 XC2ZIAInput::Macrocell{fb: 0, mc: 1},
 XC2ZIAInput::Macrocell{fb: 1, mc: 4},
 XC2ZIAInput::Macrocell{fb: 1, mc: 14}],

[XC2ZIAInput::IBuf{ibuf: 8},
 XC2ZIAInput::IBuf{ibuf: 14},
 XC2ZIAInput::IBuf{ibuf: 27},
 XC2ZIAInput::IBuf{ibuf: 31},
 XC2ZIAInput::Macrocell{fb: 0, mc: 13},
 XC2ZIAInput::Macrocell{fb: 1, mc: 6}],

[XC2ZIAInput::IBuf{ibuf: 9},
 XC2ZIAInput::IBuf{ibuf: 13},
 XC2ZIAInput::IBuf{ibuf: 25},
 XC2ZIAInput::Macrocell{fb: 0, mc: 7},
 XC2ZIAInput::Macrocell{fb: 0, mc: 10},
 XC2ZIAInput::Macrocell{fb: 1, mc: 9}],

[XC2ZIAInput::IBuf{ibuf: 8},
 XC2ZIAInput::IBuf{ibuf: 17},
 XC2ZIAInput::IBuf{ibuf: 24},
 XC2ZIAInput::Macrocell{fb: 0, mc: 5},
 XC2ZIAInput::Macrocell{fb: 1, mc: 3},
 XC2ZIAInput::Macrocell{fb: 1, mc: 5}],

[XC2ZIAInput::IBuf{ibuf: 0},
 XC2ZIAInput::IBuf{ibuf: 12},
 XC2ZIAInput::IBuf{ibuf: 23},
 XC2ZIAInput::Macrocell{fb: 0, mc: 3},
 XC2ZIAInput::Macrocell{fb: 0, mc: 15},
 XC2ZIAInput::Macrocell{fb: 1, mc: 11}],

[XC2ZIAInput::IBuf{ibuf: 1},
 XC2ZIAInput::IBuf{ibuf: 18},
 XC2ZIAInput::IBuf{ibuf: 25},
 XC2ZIAInput::Macrocell{fb: 0, mc: 6},
 XC2ZIAInput::Macrocell{fb: 1, mc: 4},
 XC2ZIAInput::Macrocell{fb: 1, mc: 5}],

[XC2ZIAInput::IBuf{ibuf: 2},
 XC2ZIAInput::IBuf{ibuf: 13},
 XC2ZIAInput::IBuf{ibuf: 30},
 XC2ZIAInput::Macrocell{fb: 0, mc: 5},
 XC2ZIAInput::Macrocell{fb: 1, mc: 2},
 XC2ZIAInput::Macrocell{fb: 1, mc: 6}],

[XC2ZIAInput::IBuf{ibuf: 3},
 XC2ZIAInput::IBuf{ibuf: 19},
 XC2ZIAInput::IBuf{ibuf: 24},
 XC2ZIAInput::Macrocell{fb: 0, mc: 0},
 XC2ZIAInput::Macrocell{fb: 1, mc: 1},
 XC2ZIAInput::Macrocell{fb: 1, mc: 14}],

[XC2ZIAInput::IBuf{ibuf: 4},
 XC2ZIAInput::DedicatedInput,
 XC2ZIAInput::IBuf{ibuf: 21},
 XC2ZIAInput::Macrocell{fb: 0, mc: 4},
 XC2ZIAInput::Macrocell{fb: 0, mc: 12},
 XC2ZIAInput::Macrocell{fb: 1, mc: 13}],

[XC2ZIAInput::IBuf{ibuf: 5},
 XC2ZIAInput::IBuf{ibuf: 17},
 XC2ZIAInput::IBuf{ibuf: 27},
 XC2ZIAInput::Macrocell{fb: 0, mc: 1},
 XC2ZIAInput::Macrocell{fb: 1, mc: 0},
 XC2ZIAInput::Macrocell{fb: 1, mc: 8}],

[XC2ZIAInput::IBuf{ibuf: 6},
 XC2ZIAInput::IBuf{ibuf: 11},
 XC2ZIAInput::IBuf{ibuf: 29},
 XC2ZIAInput::Macrocell{fb: 0, mc: 7},
 XC2ZIAInput::Macrocell{fb: 0, mc: 13},
 XC2ZIAInput::Macrocell{fb: 1, mc: 12}],

[XC2ZIAInput::IBuf{ibuf: 7},
 XC2ZIAInput::IBuf{ibuf: 10},
 XC2ZIAInput::IBuf{ibuf: 22},
 XC2ZIAInput::Macrocell{fb: 0, mc: 9},
 XC2ZIAInput::Macrocell{fb: 1, mc: 3},
 XC2ZIAInput::Macrocell{fb: 1, mc: 9}],

[XC2ZIAInput::IBuf{ibuf: 8},
 XC2ZIAInput::IBuf{ibuf: 16},
 XC2ZIAInput::IBuf{ibuf: 20},
 XC2ZIAInput::Macrocell{fb: 0, mc: 2},
 XC2ZIAInput::Macrocell{fb: 0, mc: 11},
 XC2ZIAInput::Macrocell{fb: 1, mc: 15}],

[XC2ZIAInput::IBuf{ibuf: 9},
 XC2ZIAInput::IBuf{ibuf: 15},
 XC2ZIAInput::IBuf{ibuf: 28},
 XC2ZIAInput::IBuf{ibuf: 31},
 XC2ZIAInput::Macrocell{fb: 0, mc: 14},
 XC2ZIAInput::Macrocell{fb: 1, mc: 7}],

[XC2ZIAInput::IBuf{ibuf: 9},
 XC2ZIAInput::IBuf{ibuf: 14},
 XC2ZIAInput::IBuf{ibuf: 26},
 XC2ZIAInput::Macrocell{fb: 0, mc: 8},
 XC2ZIAInput::Macrocell{fb: 0, mc: 10},
 XC2ZIAInput::Macrocell{fb: 1, mc: 10}],

[XC2ZIAInput::IBuf{ibuf: 0},
 XC2ZIAInput::IBuf{ibuf: 13},
 XC2ZIAInput::IBuf{ibuf: 24},
 XC2ZIAInput::Macrocell{fb: 0, mc: 4},
 XC2ZIAInput::Macrocell{fb: 1, mc: 0},
 XC2ZIAInput::Macrocell{fb: 1, mc: 12}],

[XC2ZIAInput::IBuf{ibuf: 1},
 XC2ZIAInput::IBuf{ibuf: 15},
 XC2ZIAInput::IBuf{ibuf: 27},
 XC2ZIAInput::Macrocell{fb: 0, mc: 9},
 XC2ZIAInput::Macrocell{fb: 0, mc: 10},
 XC2ZIAInput::Macrocell{fb: 1, mc: 11}],

[XC2ZIAInput::IBuf{ibuf: 2},
 XC2ZIAInput::IBuf{ibuf: 19},
 XC2ZIAInput::IBuf{ibuf: 26},
 XC2ZIAInput::Macrocell{fb: 0, mc: 7},
 XC2ZIAInput::Macrocell{fb: 0, mc: 11},
 XC2ZIAInput::Macrocell{fb: 1, mc: 5}],

[XC2ZIAInput::IBuf{ibuf: 3},
 XC2ZIAInput::IBuf{ibuf: 14},
 XC2ZIAInput::IBuf{ibuf: 21},
 XC2ZIAInput::Macrocell{fb: 0, mc: 6},
 XC2ZIAInput::Macrocell{fb: 1, mc: 3},
 XC2ZIAInput::Macrocell{fb: 1, mc: 7}],

[XC2ZIAInput::IBuf{ibuf: 4},
 XC2ZIAInput::IBuf{ibuf: 11},
 XC2ZIAInput::IBuf{ibuf: 25},
 XC2ZIAInput::Macrocell{fb: 0, mc: 1},
 XC2ZIAInput::Macrocell{fb: 1, mc: 2},
 XC2ZIAInput::Macrocell{fb: 1, mc: 15}],

[XC2ZIAInput::IBuf{ibuf: 5},
 XC2ZIAInput::IBuf{ibuf: 16},
 XC2ZIAInput::IBuf{ibuf: 22},
 XC2ZIAInput::Macrocell{fb: 0, mc: 5},
 XC2ZIAInput::Macrocell{fb: 0, mc: 13},
 XC2ZIAInput::Macrocell{fb: 1, mc: 14}],

[XC2ZIAInput::IBuf{ibuf: 6},
 XC2ZIAInput::IBuf{ibuf: 18},
 XC2ZIAInput::IBuf{ibuf: 28},
 XC2ZIAInput::Macrocell{fb: 0, mc: 2},
 XC2ZIAInput::Macrocell{fb: 1, mc: 1},
 XC2ZIAInput::Macrocell{fb: 1, mc: 9}],

